// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hsymczmjhelckkojourg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhzeW1jem1qaGVsY2trb2pvdXJnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI0ODExODcsImV4cCI6MjA1ODA1NzE4N30.RP_PNkIApKcvv7Dif57aNoYQ5IYLICW1VAlJJjPDcqY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);